#!/bin/bash

#find . -type f -name "*.html" -exec dos2unix {} \;

# checkout catalog version (which is overwritten without tag-cloud by new_entries)
git checkout doctruyen14.cc/truyen-sex-nguoi-lon

find . -type f -name "*.html" -mindepth 2 -maxdepth 2 -exec perl -0777 -i -pe 's/href="https:\/\/doctruyen14\.cc\/((?!feed\/|comments\/|wp-json\/|truyen-ma\/|truyen-cuoi\/|dang-truyen\/|nghe-audio-truyen-sex-mp3\/|truyen-gay\/|truyen-teen\/|truyen-tinh-cam\/|truyen-tranh\/|tag\/(?:doc-truyen-cuoi|doc-truyen-tranh|gay-18|gay-dam|gay-du-dit-dam|gay-sex|gaysex|loan-luan-gay|sex-gay|sex-gayy-dam|truyen-gay|truyen-gay-18|truyen-gay-hay-2|truyen-gay-loan-luan|truyen-gay-ngan|truyen-sex-gay-2|truyen-teen-2)\/|(?:tag\/)?(?:audio-truyen|truyen-audio))[^"]+\/(?<!feed\/)|audio-truyen-gay\/(?<!feed\/))?"/href="$1index.html"/mg' {} \;
find . -type f -name "*.html" -mindepth 3 -maxdepth 3 -exec perl -0777 -i -pe 's/href="https:\/\/doctruyen14\.cc\/((?!feed\/|comments\/|wp-json\/|truyen-ma\/|truyen-cuoi\/|dang-truyen\/|nghe-audio-truyen-sex-mp3\/|truyen-gay\/|truyen-teen\/|truyen-tinh-cam\/|truyen-tranh\/|tag\/(?:doc-truyen-cuoi|doc-truyen-tranh|gay-18|gay-dam|gay-du-dit-dam|gay-sex|gaysex|loan-luan-gay|sex-gay|sex-gayy-dam|truyen-gay|truyen-gay-18|truyen-gay-hay-2|truyen-gay-loan-luan|truyen-gay-ngan|truyen-sex-gay-2|truyen-teen-2)\/|(?:tag\/)?(?:audio-truyen|truyen-audio))[^"]+\/(?<!feed\/)|audio-truyen-gay\/(?<!feed\/))?"/href="..\/$1index.html"/mg' {} \;
find . -type f -name "*.html" -mindepth 4 -maxdepth 4 -exec perl -0777 -i -pe 's/href="https:\/\/doctruyen14\.cc\/((?!feed\/|comments\/|wp-json\/|truyen-ma\/|truyen-cuoi\/|dang-truyen\/|nghe-audio-truyen-sex-mp3\/|truyen-gay\/|truyen-teen\/|truyen-tinh-cam\/|truyen-tranh\/|tag\/(?:doc-truyen-cuoi|doc-truyen-tranh|gay-18|gay-dam|gay-du-dit-dam|gay-sex|gaysex|loan-luan-gay|sex-gay|sex-gayy-dam|truyen-gay|truyen-gay-18|truyen-gay-hay-2|truyen-gay-loan-luan|truyen-gay-ngan|truyen-sex-gay-2|truyen-teen-2)\/|(?:tag\/)?(?:audio-truyen|truyen-audio))[^"]+\/(?<!feed\/)|audio-truyen-gay\/(?<!feed\/))?"/href="..\/..\/$1index.html"/mg' {} \;
find . -type f -name "*.html" -mindepth 5 -maxdepth 5 -exec perl -0777 -i -pe 's/href="https:\/\/doctruyen14\.cc\/((?!feed\/|comments\/|wp-json\/|truyen-ma\/|truyen-cuoi\/|dang-truyen\/|nghe-audio-truyen-sex-mp3\/|truyen-gay\/|truyen-teen\/|truyen-tinh-cam\/|truyen-tranh\/|tag\/(?:doc-truyen-cuoi|doc-truyen-tranh|gay-18|gay-dam|gay-du-dit-dam|gay-sex|gaysex|loan-luan-gay|sex-gay|sex-gayy-dam|truyen-gay|truyen-gay-18|truyen-gay-hay-2|truyen-gay-loan-luan|truyen-gay-ngan|truyen-sex-gay-2|truyen-teen-2)\/|(?:tag\/)?(?:audio-truyen|truyen-audio))[^"]+\/(?<!feed\/)|audio-truyen-gay\/(?<!feed\/))?"/href="..\/..\/..\/$1index.html"/mg' {} \;
find . -type f -name "*.html" -mindepth 6 -maxdepth 6 -exec perl -0777 -i -pe 's/href="https:\/\/doctruyen14\.cc\/((?!feed\/|comments\/|wp-json\/|truyen-ma\/|truyen-cuoi\/|dang-truyen\/|nghe-audio-truyen-sex-mp3\/|truyen-gay\/|truyen-teen\/|truyen-tinh-cam\/|truyen-tranh\/|tag\/(?:doc-truyen-cuoi|doc-truyen-tranh|gay-18|gay-dam|gay-du-dit-dam|gay-sex|gaysex|loan-luan-gay|sex-gay|sex-gayy-dam|truyen-gay|truyen-gay-18|truyen-gay-hay-2|truyen-gay-loan-luan|truyen-gay-ngan|truyen-sex-gay-2|truyen-teen-2)\/|(?:tag\/)?(?:audio-truyen|truyen-audio))[^"]+\/(?<!feed\/)|audio-truyen-gay\/(?<!feed\/))?"/href="..\/..\/..\/..\/$1index.html"/mg' {} \;

find doctruyen14.cc/truyen-sex-nguoi-lon -type f -name "*.html" -exec perl -0777 -i -pe 's/\.\.\/truyen-sex-nguoi-lon\///mg' {} \;

#find . -type f -name "*.html" -exec perl -0777 -i -pe 's/mage" content="(?:\.\.\/)*((?!http)[^"]+)"/mage" content="https:\/\/baka-bon.github.io\/doctruyen14\/href"/mg' {} \;
